# Generated by Django 4.2.2 on 2023-07-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Is Neutered? (if male)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_spayed',
            field=models.BooleanField(default=False, verbose_name='Is Spayed? (if female)'),
        ),
        migrations.AddField(
            model_name='pet',
            name='is_vaccinated',
            field=models.BooleanField(default=False, verbose_name='Is Vaccinated?'),
        ),
    ]
