# Generated by Django 4.2.2 on 2023-07-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_is_neutered_pet_is_spayed_pet_is_vaccinated'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='pet_gender',
            field=models.CharField(default='NOT SPECIFIED', max_length=25, verbose_name='Gender'),
            preserve_default=False,
        ),
    ]
