# Generated by Django 4.2.2 on 2023-07-26 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_alter_pet_pet_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adopted_by',
        ),
    ]
