# Generated by Django 4.2.2 on 2023-08-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_pet_adopted_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('both', 'Both')], max_length=15, verbose_name='Animal Type'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=15, verbose_name='Gender'),
        ),
    ]
