# Generated by Django 4.2.2 on 2023-07-26 10:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('petID', models.AutoField(primary_key=True, serialize=False)),
                ('pet_name', models.CharField(max_length=50)),
                ('animal_type', models.CharField(max_length=25)),
                ('breed', models.CharField(max_length=50)),
                ('pet_age', models.PositiveSmallIntegerField()),
                ('size', models.CharField(max_length=25)),
                ('color', models.CharField(max_length=25)),
                ('personality', models.CharField(max_length=50)),
                ('healthcondition', models.CharField(max_length=100)),
                ('pet_description', models.CharField(max_length=300)),
                ('adoption_status', models.CharField(max_length=20)),
                ('pet_img_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staffID', models.AutoField(primary_key=True, serialize=False)),
                ('job_position', models.CharField(max_length=50)),
                ('st_fullname', models.CharField(max_length=50)),
                ('st_email', models.CharField(max_length=100)),
                ('st_password', models.CharField(max_length=50)),
                ('st_address', models.CharField(max_length=100)),
                ('st_phone_no', models.CharField(max_length=25)),
                ('adoptions_assisted', models.PositiveIntegerField(null=True)),
                ('date_hired', models.DateField(default=datetime.datetime(2023, 7, 26, 10, 55, 30, 627504, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('user_fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('email_address', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=25)),
                ('user_bio', models.CharField(max_length=300, null=True)),
                ('datejoined', models.DateField(default=datetime.datetime(2023, 7, 26, 10, 55, 30, 627504, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('preferenceID', models.AutoField(primary_key=True, serialize=False)),
                ('pf_animal_type', models.CharField(max_length=50, null=True)),
                ('pf_breed', models.CharField(max_length=50, null=True)),
                ('pf_age', models.CharField(max_length=5, null=True)),
                ('pf_size', models.CharField(max_length=25, null=True)),
                ('pf_color', models.CharField(max_length=25, null=True)),
                ('pf_personality', models.CharField(max_length=50, null=True)),
                ('pf_healthcondition', models.CharField(max_length=100, null=True)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.user')),
            ],
        ),
        migrations.CreateModel(
            name='UserApplications',
            fields=[
                ('applicationID', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('comments', models.CharField(max_length=300, null=True)),
                ('petID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.pet')),
                ('staffID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.staff')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.user')),
            ],
        ),
        migrations.AddField(
            model_name='pet',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user'),
        ),
    ]
