# Generated by Django 4.2.2 on 2023-07-26 12:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_userapplications_petid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='adoption_status',
        ),
        migrations.AlterField(
            model_name='pet',
            name='adopted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.user', verbose_name='Adopted By'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(max_length=25, verbose_name='Animal Type'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='breed',
            field=models.CharField(max_length=50, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='color',
            field=models.CharField(max_length=25, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='healthcondition',
            field=models.CharField(max_length=100, verbose_name='Health Condition'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False, verbose_name='Is Adopted?'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='personality',
            field=models.CharField(max_length=50, verbose_name='Personality'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='petID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Pet ID'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_age',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_description',
            field=models.CharField(max_length=300, verbose_name='Pet Description'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_img_url',
            field=models.CharField(max_length=255, verbose_name='Pet Image URL'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_name',
            field=models.CharField(max_length=50, verbose_name='Pet Name'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(max_length=25, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=100, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='datejoined',
            field=models.DateField(default=datetime.datetime(2023, 7, 26, 12, 20, 42, 221753, tzinfo=datetime.timezone.utc), verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.CharField(max_length=100, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_no',
            field=models.CharField(max_length=25, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='userID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(null=True, verbose_name='User Bio'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_fullname',
            field=models.CharField(max_length=100, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=50, verbose_name='Username'),
        ),
    ]
