# Generated by Django 4.2.2 on 2023-07-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_pet_adoption_status_alter_pet_adopted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='datejoined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Joined'),
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
