# Generated by Django 4.2.2 on 2023-07-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_user_datejoined_delete_pet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='user_fname',
            field=models.CharField(default='NULL', max_length=100, verbose_name='First Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='user_lname',
            field=models.CharField(default='NULL', max_length=100, verbose_name='Last Name'),
            preserve_default=False,
        ),
    ]
