# Generated by Django 4.2.2 on 2023-07-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_user_user_fullname_user_user_fname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_bio',
            field=models.TextField(blank=True, null=True, verbose_name='User Bio'),
        ),
    ]
