# Generated by Django 4.2.2 on 2023-07-26 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_user_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_bio',
        ),
    ]
