# Generated by Django 4.2.2 on 2023-07-31 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_preference_userid_preference_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preference',
            old_name='pf_healthcondition',
            new_name='pf_healthconditio',
        ),
    ]
