# Generated by Django 4.2.2 on 2023-07-31 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_rename_pf_healthcondition_preference_pf_healthconditio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='userID',
        ),
    ]
