# Generated by Django 4.2.2 on 2023-07-31 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0016_remove_preference_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='pf_healthconditio',
        ),
        migrations.AddField(
            model_name='preference',
            name='has_medicalcondition',
            field=models.BooleanField(default=False, verbose_name='Has medical condition?'),
        ),
        migrations.AddField(
            model_name='preference',
            name='is_neutered',
            field=models.BooleanField(default=False, verbose_name='Neutered?'),
        ),
        migrations.AddField(
            model_name='preference',
            name='is_spayed',
            field=models.BooleanField(default=False, verbose_name='Spayed?'),
        ),
        migrations.AddField(
            model_name='preference',
            name='pf_healthcondition',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Health Condition'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_age',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_animal_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Animal Type'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_breed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Breed'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_color',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_personality',
            field=models.CharField(blank=True, choices=[('friendly', 'Friendly'), ('playful', 'Playful'), ('calm', 'Calm'), ('shy', 'Shy'), ('energetic', 'Energetic'), ('loyal', 'Loyal'), ('smart', 'Smart'), ('social', 'Social'), ('curious', 'Curious'), ('independent', 'Independent'), ('affectionate', 'Affectionate')], max_length=50, null=True, verbose_name='Personality'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_size',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='size'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='preferenceID',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Preference ID'),
        ),
        migrations.AlterField(
            model_name='preference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='From User:'),
        ),
    ]
