# Generated by Django 4.2.2 on 2023-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_preference_pf_healthconditio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='pf_personality',
            field=models.CharField(blank=True, choices=[('friendly', 'Friendly'), ('playful', 'Playful'), ('calm', 'Calm'), ('shy', 'Shy'), ('energetic', 'Energetic'), ('loyal', 'Loyal'), ('smart', 'Smart'), ('social', 'Social'), ('curious', 'Curious'), ('independent', 'Independent'), ('affectionate', 'Affectionate')], default='NULL', max_length=150),
            preserve_default=False,
        ),
    ]
