# Generated by Django 4.2.2 on 2023-07-31 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_preference_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='pf_gender',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gender'),
        ),
    ]
