# Generated by Django 4.2.2 on 2023-08-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_preference_pf_animal_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='pf_healthcondition',
        ),
        migrations.AlterField(
            model_name='preference',
            name='pf_personality',
            field=models.CharField(blank=True, max_length=150, verbose_name='Personalities:'),
        ),
    ]
